import { StaticPageShell, PageSection } from "./StaticPageShell";

const GITHUB_URL = "https://github.com/KunjShah95/archmind-ai";

export default function Terms() {
  return (
    <StaticPageShell title="Terms of Service">
      <PageSection title="1. Agreement">
        <p>
          These Terms of Service ("Terms") govern your use of the hosted ArchMind AI service
          ("Service") operated by ArchMind AI, Inc. By creating an account or using the Service,
          you agree to these Terms. If you are using the Service on behalf of an organization, you
          represent that you have authority to bind that organization.
        </p>
        <p>
          Self-hosted deployments of the open-source code are governed by the license in the{" "}
          <a
            href={GITHUB_URL}
            target="_blank"
            rel="noreferrer"
            className="text-primary hover:underline"
          >
            GitHub repository
          </a>
          , not by these Terms.
        </p>
      </PageSection>

      <PageSection title="2. The Service">
        <p>
          ArchMind analyzes software architecture diagrams using AI agents and produces findings,
          scores, and recommendations. Analysis output is generated by large language models and is
          provided for informational purposes only — it is not a substitute for professional
          engineering judgment, a security audit, or compliance advice. You are responsible for
          validating any recommendation before acting on it.
        </p>
      </PageSection>

      <PageSection title="3. Accounts">
        <p>
          You must provide accurate account information and keep your credentials secure. You are
          responsible for all activity under your account. Notify us promptly of any unauthorized
          use.
        </p>
      </PageSection>

      <PageSection title="4. Acceptable use">
        <p>You agree not to:</p>
        <ul className="list-disc pl-5 space-y-2">
          <li>Upload content you do not have the right to share, including confidential third-party material.</li>
          <li>Use the Service to develop, plan, or facilitate illegal activity or attacks on systems you do not own or have permission to test.</li>
          <li>Attempt to probe, scan, or breach the Service's security, or access other customers' data.</li>
          <li>Resell, sublicense, or provide the hosted Service to third parties without our consent.</li>
          <li>Use automated means to place excessive load on the Service or circumvent rate limits and plan quotas.</li>
          <li>Misrepresent AI-generated analysis output as an independent professional audit.</li>
        </ul>
      </PageSection>

      <PageSection title="5. Your content and intellectual property">
        <p>
          You retain all rights to the diagrams, prompts, and other content you upload ("Customer
          Content"). You grant us a limited license to host, process, and display Customer Content
          solely to provide the Service to you, including transmitting it to the LLM providers you
          configure. We do not use Customer Content to train models.
        </p>
        <p>
          The Service, including its software, design, and branding, is owned by ArchMind AI, Inc.
          and its licensors. Open-source components remain under their respective licenses. Subject
          to these Terms, we grant you a non-exclusive, non-transferable right to use the Service
          during your subscription.
        </p>
        <p>
          Analysis reports generated for you may be used freely within your organization, including
          in RFCs, decision records, and internal documentation.
        </p>
      </PageSection>

      <PageSection title="6. Third-party services">
        <p>
          The Service can integrate with third-party LLM providers, source-control platforms, and
          messaging tools that you configure. Your use of those services is governed by their own
          terms, and we are not responsible for their availability or conduct.
        </p>
      </PageSection>

      <PageSection title="7. Plans, billing, and cancellation">
        <p>
          Free plans are provided as-is with usage limits. Paid plans renew automatically until
          cancelled; you can cancel at any time and retain access until the end of the current
          billing period. Fees are non-refundable except where required by law. We may change
          pricing with reasonable advance notice.
        </p>
      </PageSection>

      <PageSection title="8. Disclaimers">
        <p>
          THE SERVICE IS PROVIDED "AS IS" AND "AS AVAILABLE" WITHOUT WARRANTIES OF ANY KIND,
          WHETHER EXPRESS, IMPLIED, OR STATUTORY, INCLUDING WARRANTIES OF MERCHANTABILITY, FITNESS
          FOR A PARTICULAR PURPOSE, AND NON-INFRINGEMENT. AI-GENERATED OUTPUT MAY CONTAIN ERRORS OR
          OMISSIONS, AND WE DO NOT WARRANT ITS ACCURACY OR COMPLETENESS.
        </p>
      </PageSection>

      <PageSection title="9. Limitation of liability">
        <p>
          TO THE MAXIMUM EXTENT PERMITTED BY LAW, ARCHMIND AI, INC. WILL NOT BE LIABLE FOR ANY
          INDIRECT, INCIDENTAL, SPECIAL, CONSEQUENTIAL, OR PUNITIVE DAMAGES, OR FOR LOST PROFITS,
          REVENUES, DATA, OR GOODWILL, ARISING FROM OR RELATED TO YOUR USE OF THE SERVICE. OUR
          TOTAL AGGREGATE LIABILITY FOR ALL CLAIMS ARISING OUT OF THESE TERMS WILL NOT EXCEED THE
          AMOUNTS YOU PAID US FOR THE SERVICE IN THE TWELVE (12) MONTHS BEFORE THE EVENT GIVING
          RISE TO THE CLAIM (OR US $100 IF YOU USE ONLY THE FREE PLAN). SOME JURISDICTIONS DO NOT
          ALLOW THESE LIMITATIONS, SO THEY MAY NOT APPLY TO YOU.
        </p>
      </PageSection>

      <PageSection title="10. Indemnification">
        <p>
          You will indemnify and hold us harmless from claims arising out of your Customer Content,
          your violation of these Terms, or your violation of any third-party rights.
        </p>
      </PageSection>

      <PageSection title="11. Termination">
        <p>
          You may stop using the Service and delete your account at any time. We may suspend or
          terminate access for material breach of these Terms, with notice where practicable. Upon
          termination, your right to use the Service ends and we will delete Customer Content in
          accordance with our Privacy Policy.
        </p>
      </PageSection>

      <PageSection title="12. Changes to these Terms">
        <p>
          We may update these Terms from time to time. Material changes will be announced via the
          repository or the Service, and continued use after the effective date constitutes
          acceptance of the updated Terms.
        </p>
      </PageSection>

      <PageSection title="13. Contact">
        <p>
          Questions about these Terms? Open an issue on{" "}
          <a
            href={`${GITHUB_URL}/issues`}
            target="_blank"
            rel="noreferrer"
            className="text-primary hover:underline"
          >
            GitHub
          </a>
          .
        </p>
      </PageSection>
    </StaticPageShell>
  );
}
