"""Generate architecture documentation from an analyzed diagram.

Two document types, both deterministic markdown built from the stored
analysis (nodes, edges, findings, scores, mediator report):

- ``readme``: an architecture overview doc suitable for a repo README or wiki.
- ``adr``: an Architecture Decision Record capturing the review outcome.
"""

from datetime import date
from typing import Any

DOC_TYPES = ("readme", "adr", "deployment-guide", "runbook")

_SEVERITY_ORDER = ["critical", "high", "medium", "low"]


def _label(node: dict[str, Any]) -> str:
    return (node.get("data") or {}).get("label") or node.get("id", "component")


def _sorted_findings(findings: list[dict[str, Any]]) -> list[dict[str, Any]]:
    return sorted(
        findings,
        key=lambda f: _SEVERITY_ORDER.index(f["severity"])
        if f["severity"] in _SEVERITY_ORDER else 9,
    )


def build_readme(
    name: str,
    nodes: list[dict[str, Any]],
    edges: list[dict[str, Any]],
    scores: dict[str, int],
    findings: list[dict[str, Any]],
) -> str:
    labels = {n.get("id"): _label(n) for n in nodes}
    avg = round(sum(scores.values()) / len(scores)) if scores else 0

    lines = [
        f"# {name} — Architecture Overview",
        "",
        f"> Generated by ArchMind AI on {date.today().isoformat()}. "
        f"Overall architecture score: **{avg}/100**.",
        "",
        "## Components",
        "",
    ]
    if labels:
        lines += [f"- **{label}**" for label in labels.values()]
    else:
        lines.append("_No components detected._")

    lines += ["", "## Data & Control Flow", ""]
    if edges:
        for e in edges:
            src = labels.get(e.get("source"), e.get("source", "?"))
            dst = labels.get(e.get("target"), e.get("target", "?"))
            lines.append(f"- {src} → {dst}")
    else:
        lines.append("_No connections detected._")

    lines += ["", "## Quality Scores", ""]
    lines += ["| Dimension | Score |", "|---|---|"]
    lines += [f"| {k.capitalize()} | {v}/100 |" for k, v in sorted(scores.items())]

    top = _sorted_findings(findings)[:10]
    lines += ["", "## Known Risks & Recommendations", ""]
    if top:
        for f in top:
            lines += [
                f"### {f['title']} ({f['severity']})",
                f"{f['summary']}",
                "",
                f"**Recommendation:** {f['recommendation']}",
                "",
            ]
    else:
        lines.append("_No findings._")

    return "\n".join(lines)


def build_adr(
    name: str,
    scores: dict[str, int],
    findings: list[dict[str, Any]],
    mediator_report: dict[str, Any] | None,
) -> str:
    avg = round(sum(scores.values()) / len(scores)) if scores else 0
    top = _sorted_findings(findings)
    blocking = [f for f in top if f["severity"] in ("critical", "high")]

    status = "Accepted" if not blocking else "Proposed — blocking findings open"
    lines = [
        f"# ADR: Architecture review of {name}",
        "",
        f"- **Date:** {date.today().isoformat()}",
        f"- **Status:** {status}",
        f"- **Overall score:** {avg}/100",
        "",
        "## Context",
        "",
        f"A multi-agent architecture review of *{name}* was performed across "
        f"{len(scores)} quality dimensions "
        f"({', '.join(sorted(scores))}).",
        "",
        "## Decision",
        "",
    ]
    if blocking:
        lines += [
            f"The architecture is adopted **conditionally**. {len(blocking)} "
            "critical/high finding(s) must be resolved:",
            "",
            *(f"1. **{f['title']}** — {f['recommendation']}" for f in blocking),
        ]
    else:
        lines.append("The architecture is adopted as reviewed. No blocking findings.")

    if mediator_report and mediator_report.get("summary"):
        lines += ["", "## Review board synthesis", "", str(mediator_report["summary"])]

    lines += ["", "## Consequences", ""]
    others = [f for f in top if f["severity"] in ("medium", "low")][:8]
    if others:
        lines.append("Accepted (non-blocking) trade-offs to track:")
        lines += [f"- {f['title']} ({f['severity']}): {f['summary']}" for f in others]
    else:
        lines.append("No outstanding trade-offs recorded.")

    return "\n".join(lines)


def build_deployment_guide(
    name: str,
    nodes: list[dict[str, Any]],
    edges: list[dict[str, Any]],
    scores: dict[str, int],
    findings: list[dict[str, Any]],
) -> str:
    labels = {n.get("id"): _label(n) for n in nodes}
    avg = round(sum(scores.values()) / len(scores)) if scores else 0

    lines = [
        f"# {name} — Deployment Guide",
        "",
        f"> Generated by ArchMind AI on {date.today().isoformat()}. "
        f"Architecture score: **{avg}/100**.",
        "",
        "## Prerequisites",
        "",
        "- Cloud provider account with appropriate permissions",
        "- Container runtime (Docker / containerd)",
        "- Kubernetes cluster (minimum 3 nodes recommended)",
        "- CI/CD pipeline configured",
        "",
        "## Components to Deploy",
        "",
    ]
    if labels:
        lines += [f"- **{label}**" for label in labels.values()]
    else:
        lines.append("_No components detected._")

    lines += ["", "## Deployment Order", ""]
    if edges:
        # topological-ish order: list unique targets in edge order
        deployed = set()
        for e in edges:
            src = labels.get(e.get("source"), e.get("source", "?"))
            dst = labels.get(e.get("target"), e.get("target", "?"))
            if src not in deployed:
                lines.append(f"1. Deploy **{src}**")
                deployed.add(src)
            if dst not in deployed:
                lines.append(f"1. Deploy **{dst}**")
                deployed.add(dst)
    else:
        for label in (labels.values()):
            lines.append(f"1. Deploy **{label}**")

    blocking = _sorted_findings(findings)[:5]
    if blocking:
        lines += ["", "## Known Deployment Risks", ""]
        for f in blocking:
            lines += [
                f"- **{f['title']}** ({f['severity']})",
                f"  - Mitigation: {f['recommendation']}",
            ]

    lines += ["", "## Post-Deployment Verification", "",
               "- Verify all pods are running: `kubectl get pods --all-namespaces`",
               "- Check service endpoints: `kubectl get svc`",
               "- Monitor error rates and latency in your observability dashboard",
               "- Run a smoke test against the public API endpoint"]

    return "\n".join(lines)


def build_runbook(
    name: str,
    scores: dict[str, int],
    findings: list[dict[str, Any]],
) -> str:
    avg = round(sum(scores.values()) / len(scores)) if scores else 0
    top = _sorted_findings(findings)
    critical = [f for f in top if f["severity"] in ("critical", "high")]

    lines = [
        f"# {name} — Operations Runbook",
        "",
        f"> Generated by ArchMind AI on {date.today().isoformat()}. "
        f"Architecture score: **{avg}/100**.",
        "",
        "## System Overview",
        "",
        f"Automated runbook for *{name}* covering operational procedures "
        "based on architecture analysis findings.",
        "",
        "## Alert Response Procedures",
        "",
    ]
    if critical:
        for i, f in enumerate(critical[:10], 1):
            lines += [
                f"### {i}. {f['title']}",
                "",
                f"- **Severity:** {f['severity'].upper()}",
                "- **Detection:** Monitor for signs matching this finding",
                f"- **Impact:** {f['summary']}",
                f"- **Response:** {f['recommendation']}",
                "",
            ]
    else:
        lines += ["_No critical or high-severity alerts defined._", ""]

    lines += [
        "## Health Checks",
        "",
        "- Check service health endpoints (`/health`, `/ready`)",
        "- Verify database connection pool utilization",
        "- Review cache hit ratio and eviction rates",
        "- Monitor queue depths and consumer lag",
        "- Validate TLS certificate expiry dates",
        "",
        "## Escalation Path",
        "",
        "1. **Tier 1** — On-call engineer (automated remediation)",
        "2. **Tier 2** — Platform team (within 1 hour)",
        "3. **Tier 3** — Architecture review (within 24 hours)",
    ]

    return "\n".join(lines)


def build_doc(
    doc_type: str,
    name: str,
    nodes: list[dict[str, Any]],
    edges: list[dict[str, Any]],
    scores: dict[str, int],
    findings: list[dict[str, Any]],
    mediator_report: dict[str, Any] | None,
) -> dict[str, str]:
    if doc_type == "readme":
        md = build_readme(name, nodes, edges, scores, findings)
        suffix = "architecture"
    elif doc_type == "adr":
        md = build_adr(name, scores, findings, mediator_report)
        suffix = "adr"
    elif doc_type == "deployment-guide":
        md = build_deployment_guide(name, nodes, edges, scores, findings)
        suffix = "deployment-guide"
    elif doc_type == "runbook":
        md = build_runbook(name, scores, findings)
        suffix = "runbook"
    else:
        raise ValueError(f"Unknown doc type. Choose one of: {', '.join(DOC_TYPES)}")

    safe = "".join(c if c.isalnum() or c in "._-" else "_" for c in name)[:60]
    return {"filename": f"{safe}-{suffix}.md", "markdown": md}
